-- MySQL Script generated by MySQL Workbench
-- Thu Mar 28 15:54:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema fileremotedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fileremotedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fileremotedb` DEFAULT CHARACTER SET utf8 ;
USE `fileremotedb` ;

-- -----------------------------------------------------
-- Table `fileremotedb`.`utilizador_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fileremotedb`.`utilizador_log` ;

CREATE TABLE IF NOT EXISTS `fileremotedb`.`utilizador_log` (
  `Email` VARCHAR(50) NULL,
  `NomeUtilizador` VARCHAR(100) NULL,
  `CategoriaProfissional` VARCHAR(300) NULL,
  `Utilizador` VARCHAR(100) NULL,
  `data_operacao` TIMESTAMP(6) NULL,
  `operacao` VARCHAR(1) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fileremotedb`.`cultura_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fileremotedb`.`cultura_log` ;

CREATE TABLE IF NOT EXISTS `fileremotedb`.`cultura_log` (
  `IDCultura` INT NULL,
  `NomeCultura` VARCHAR(100) NULL,
  `DescricaoCultura` TEXT NULL,
  `Utilizador_Email` VARCHAR(50) NULL,
  `utilizador` VARCHAR(100) NULL,
  `data_operacao` TIMESTAMP(6) NULL,
  `operacao` VARCHAR(1) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fileremotedb`.`sistema_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fileremotedb`.`sistema_log` ;

CREATE TABLE IF NOT EXISTS `fileremotedb`.`sistema_log` (
  `LimiteInferiorTemperatura` DECIMAL(8,2) NULL,
  `LimiteSuperiorTemperatura` DECIMAL(8,2) NULL,
  `LimiteSuperiorLuz` DECIMAL(8,2) NULL,
  `LimiteInferiorLuz` DECIMAL(8,2) NULL,
  `utilizador` VARCHAR(100) NULL,
  `data_operacao` TIMESTAMP(6) NULL,
  `operacao` VARCHAR(1) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fileremotedb`.`medicao_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fileremotedb`.`medicao_log` ;

CREATE TABLE IF NOT EXISTS `fileremotedb`.`medicao_log` (
  `NumeroMedicao` INT NULL,
  `DataHoraMedicao` TIMESTAMP(6) NULL,
  `ValorMedicao` DECIMAL(8,2) NULL,
  `IDCultura` INT NULL,
  `VariaveisMedidas_IDVariavel` INT NULL,
  `utilizador` VARCHAR(100) NULL,
  `data_operacao` TIMESTAMP(6) NULL,
  `operacao` VARCHAR(1) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fileremotedb`.`variavel_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fileremotedb`.`variavel_log` ;

CREATE TABLE IF NOT EXISTS `fileremotedb`.`variavel_log` (
  `IDvariavel` INT NULL,
  `NomeVariavel` VARCHAR(100) NULL,
  `utilizador` VARCHAR(100) NULL,
  `data_operacao` TIMESTAMP(6) NULL,
  `opercao` VARCHAR(1) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `fileremotedb`.`variaveis_medidas_log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `fileremotedb`.`variaveis_medidas_log` ;

CREATE TABLE IF NOT EXISTS `fileremotedb`.`variaveis_medidas_log` (
  `LimiteInferior` DECIMAL(8,2) NULL,
  `LimiteSuperior` DECIMAL(8,2) NULL,
  `Variavel_IDVariavel` INT NULL,
  `Cultura_IDCultura` INT NULL,
  `utilizador` VARCHAR(100) NULL,
  `data_operacao` TIMESTAMP(6) NULL,
  `operacao` VARCHAR(1) NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

SET SQL_MODE = '';
DROP USER IF EXISTS Auditor;
SET SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
CREATE USER 'Auditor';

GRANT SELECT ON TABLE `fileremotedb`.* TO 'Auditor';
GRANT SELECT ON TABLE `fileremotedb`.`sistema_log` TO 'Auditor';
GRANT SELECT ON TABLE `fileremotedb`.`cultura_log` TO 'Auditor';
GRANT SELECT ON TABLE `fileremotedb`.`variavel_log` TO 'Auditor';
GRANT SELECT ON TABLE `fileremotedb`.`utilizador_log` TO 'Auditor';
GRANT SELECT ON TABLE `fileremotedb`.`medicao_log` TO 'Auditor';
GRANT SELECT ON TABLE `fileremotedb`.`variaveis_medidas_log` TO 'Auditor';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
